# Exploring how organisms respond to global change in an ecological context

## Research interests

Broadly, I am interested in how species are responding to the unintended natural experiment of global change driven by humans. I'm motivated to explore how **multiple stressors** impact species responses and how these responses **change across time and space**. In exploring these responses, I study **evolution on rapid time scales** and **plasticity** as responses to novel environmental conditions.

My previous research investigated these responses in the realm of **urbanization** in two ways: 

  1. Using the urbanization gradient as a 'space for time substitution' to explore how urban populations are evolving to the urban heat island compared to non-urban populations, I've used populations of a native ant species to explore the evolution of **thermal physiology** to the urban heat island during **winter**. 
  
  2. I've used populations of a Collembolan (springtail) within a single urban area to test how environmental variation of **multiple traits (temperature and salinity)** at small spatial scales affects the evolution of physiological traits.

Presently, I aim to continue exploring adaptation across seasons with a focus on the overwintering period for insects, adaptation to multiple stressors, and tradeoffs in physiological traits. To expand my research I am interested in how these responses fit into the **dynamics** between ecology and evolution (eco-evo dynamics) and how responses of one species can feedback to influence other species, communities of organisms, and entire ecosystems.

## Influential papers, work, and media;

These are a few selected papers, books, and projects that have influenced my thinking in this field and that continue to excite me with new ideas when I review them!

 - Papers:
 
 - Books:
 
 - Projects / Systems / Ideas:
 
 - Podcasts and video series:
 
